### ISSUE TITLE
EditSupplier.cshtml page

### ISSUE THREAD

**Issue by raakitsan** [markjprice/web-dev-net9#1]
In chapter 3, Inserting, updating, and deleting suppliers section, the code for EditSupplier.cshtml doesn't seem to display the contents of the three fields for editing. Also, with fields populated, and submit button clicked, enters [http post] Edit Supplier method with ModelState.IsValid as false.

**Comment by markjprice** [comment]
Hmmm, I'm not sure why your code isn't working. Have you compared it to the code solutions on GitHub?
Here's a screenshot of me editing the first supplier to add a "2" to the end of the name:
![image](https://github.com/user-attachments/assets/131bb4b1-7a0d-4cc8-b0c2-151254f09813)

**Comment by raakitsan** [comment]
Found problem in the, "...  controller code ... for GET supplier:".
Book shows, "EditSupplier(int? supplierId)". I changed my code to match
GitHub code solution, "EditSupplier(int? id)"; all is well for now.

**Comment by markjprice** [comment]
Ah, thank you for spotting this mistake in the print book. Luckily, I can get this fixed in the proofs before it goes to the printer and the final book is uploaded for ebooks.
