### ISSUE TITLE
Testing the class libraries - Failed Build on Microsoft.NET.Test.Sdk

### ISSUE THREAD

**Issue by robyyo** [markjprice/web-dev-net9#2]
While attempting to build the Northwind.UnitTests project to build referenced projects I ran into an error related to the PackageVersion for Microsoft.NET.Test.Sdk. The book references Version="18.0.0" but on checking Nuget.org I was only able to find "17.12.0".

I switched to 17.12.0 and the dependency error resolved.

**Comment by robyyo** [comment]
> Hmmm, I do not yet have a final published version of the paperback or PDF or online ebook to see for myself. When you say the "book references Version="18.0.0"", what format are you reading? Paperback? PDF? Online web ebook?
> 
> In my last "prefinal" proofs before publishing, the `Northwind.UnitTests` project did not specify a package version and matches the online solution here: https://github.com/markjprice/web-dev-net9/blob/main/code/MatureWeb/Northwind.UnitTests/Northwind.UnitTests.csproj#L12
> 
> And the online solution for centrally managing the package version is here and uses `17.12.0`: https://github.com/markjprice/web-dev-net9/blob/main/code/MatureWeb/Directory.Packages.props#L15
> 
> Hopefully I will get a final version of the paperback and ebook formats in the next couple of weeks and I will update this issue if needed.

![image](https://github.com/user-attachments/assets/8f4bc330-c6c0-47ef-8707-b92ac12242e9)

I'm reading online using Packt's website. I didn't check the repo to see what was actually in the code, probably should have. Thanks.

**Comment by markjprice** [comment]
That looks like a very early book preliminary draft (that is used as an Early Release edition) when I was guessing that Visual Studio would be branded as 2025 and be version 18.0.0. I will ask Packt to make sure the online book has been properly updated to the final drafts. Sometimes the process takes a few days so it might already be fixed. Or someone might have missed a step. Thank you for raising this issue.

**Comment by robyyo** [comment]
> That looks like a very early book preliminary draft (that is used as an Early Release edition) when I was guessing that Visual Studio would be branded as 2025 and be version 18.0.0. I will ask Packt to make sure the online book has been properly updated to the final drafts. Sometimes the process takes a few days so it might already be fixed. Or someone might have missed a step. Thank you for raising this issue.

Sounds good, thanks!

**Comment by markjprice** [comment]
I've added an errata item for this here:
https://github.com/markjprice/web-dev-net9/blob/main/docs/errata/errata.md#page-15---central-package-management
